for name <- [
      "OOOLALA_MAX_USERS",
      "OOOLALA_SIGNUP_DAILY_LIMIT",
      "OOOLALA_SIGNUP_HOURLY_LIMIT",
      "OOOLALA_MESSAGE_RATE_LIMIT_COUNT",
      "OOOLALA_MESSAGE_RATE_LIMIT_WINDOW_SECONDS",
      "OOOLALA_MAX_MESSAGE_BYTES",
      "OOOLALA_MAX_ATTACHMENTS",
      "OOOLALA_MAX_ATTACHMENT_BYTES",
      "OOOLALA_MAX_ATTACHMENTS_TOTAL_BYTES"
    ] do
  System.delete_env(name)
end

ExUnit.start()
